(function(){
'use strict';
const $=id=>document.getElementById(id);
const S={all:[],filtered:[],idx:0,dict:null,broad:null,learned:{},mode:'all'};
const LS='dh_clean_v2_state';
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-zğüşöçıİĞÜŞÖÇ0-9 ]+/g,' ').replace(/\s+/g,' ').trim()}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.remove('show'),2200)}
function loadState(){try{Object.assign(S,JSON.parse(localStorage.getItem(LS)||'{}'));S.learned=S.learned||{}}catch(e){}}
function saveState(){localStorage.setItem(LS,JSON.stringify({idx:S.idx,learned:S.learned,mode:S.mode}))}
async function fetchJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(url);return r.json()}
async function loadXlsx(){await waitForXLSX();const ab=await (await fetch('data/cumleler.xlsx',{cache:'no-store'})).arrayBuffer();const wb=XLSX.read(ab,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});S.all=rows.map((r,i)=>({id:'s'+i,word:r.word||'',translation:r.translation||'',phonetic:r.phonetic||'',sentence:r.sentence||'',sentenceTr:r.sentenceTr||'',highlights:String(r.highlights||'').split(/[,;|]+/).map(x=>x.trim()).filter(Boolean),sentenceLevel:r.sentenceLevel||'',grammarStructure:r.grammarStructure||''})).filter(x=>x.sentence)}
function waitForXLSX(){return new Promise((res,rej)=>{let n=0;(function chk(){if(window.XLSX)return res();if(++n>80)return rej(Error('XLSX kütüphanesi yüklenmedi'));setTimeout(chk,100)})()})}
async function init(){bind();loadState();try{await loadXlsx();$('statusText').textContent=S.all.length+' cümle yüklendi';S.filtered=S.all.slice();render();renderList();loadDicts();}catch(e){$('sentenceText').textContent='cumleler.xlsx yüklenemedi';$('sentenceTr').textContent='data/cumleler.xlsx dosyasının GitHub klasöründe olduğundan emin ol.';console.error(e)}}
async function loadDicts(){try{S.dict=await fetchJSON('data/sozluk.json')}catch(e){S.dict=[]}try{S.broad=await fetchJSON('data/firatkaya_simple.json')}catch(e){S.broad=[]}}
function current(){return S.filtered[S.idx]||S.all[0]||{}}
function learnInfo(x){return S.learned[x.id]||null}
function render(){if(!S.filtered.length)return;const x=current(), li=learnInfo(x);$('activeListTitle').textContent=S.mode==='due'?'Bugün Çalışılacaklar':'Cümle Listesi';$('sentenceText').textContent=x.sentence;$('sentenceTr').textContent=x.sentenceTr||'Türkçe çeviri yok';$('levelBadge').textContent='Seviye: '+(x.sentenceLevel||'-');$('grammarBadge').textContent='Gramer: '+(x.grammarStructure||'-');$('highlights').innerHTML=(x.highlights||[]).map(h=>`<span>${esc(h)}</span>`).join('');$('learnState').textContent=li?('Başlandı • tekrar: '+new Date(li.next).toLocaleString('tr-TR')):'Henüz çalışılmadı';$('learnCard').classList.toggle('due',!!li && li.next<=Date.now());$('quickStats').textContent=`${S.idx+1}/${S.filtered.length} • Başlanan: ${Object.keys(S.learned).length}`;renderWordInfo(x);saveState()}
function renderWordInfo(x){const parts=[];if(x.word)parts.push(`<b>${esc(x.word)}</b>`);if(x.translation)parts.push(esc(x.translation));if(x.phonetic)parts.push('Okunuş: '+esc(x.phonetic));$('wordInfo').innerHTML=parts.join('<br>')||'Kelime bilgisi yok.'}
function renderList(){const q=norm($('searchInput').value);let arr=S.mode==='due'?dueItems():S.all;if(q)arr=arr.filter(x=>norm([x.sentence,x.sentenceTr,x.word,x.translation,x.grammarStructure,x.sentenceLevel].join(' ')).includes(q));S.filtered=arr;S.idx=Math.min(S.idx,Math.max(0,S.filtered.length-1));$('sentenceList').innerHTML=arr.slice(0,300).map((x,i)=>itemHTML(x,i)).join('')+(arr.length>300?`<div class="muted">İlk 300 sonuç gösteriliyor. Arama kullan.</div>`:'');renderReview();render()}
function itemHTML(x,i){const l=learnInfo(x);return `<div class="item ${l?'learned':''}" data-jump="${i}"><b>${esc(x.sentence)}</b><small>${esc(x.sentenceTr||'')}<br>${esc(x.sentenceLevel||'-')} • ${esc(x.grammarStructure||'-')}</small></div>`}
function dueItems(){const now=Date.now();return S.all.filter(x=>S.learned[x.id]&&S.learned[x.id].next<=now)}
function renderReview(){const d=dueItems();$('reviewList').innerHTML=d.length?d.map((x,i)=>`<div class="item due" data-review="${x.id}"><b>${esc(x.sentence)}</b><small>${esc(x.sentenceTr||'')}</small></div>`).join(''):'<p class="muted">Bugün tekrar zamanı gelen cümle yok.</p>'}
function markLearn(){const x=current();const old=S.learned[x.id]||{count:0};const count=old.count+1;const days=[1,3,7,14,30,60][Math.min(count-1,5)];S.learned[x.id]={started:old.started||Date.now(),last:Date.now(),next:Date.now()+days*86400000,count};toast('Kaydedildi. Sonraki tekrar: '+days+' gün sonra');render();renderList()}
function speak(text){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.88;speechSynthesis.speak(u)}
function openDrawer(){ $('drawer').classList.add('open'); $('shade').classList.add('show') }
function closeDrawer(){ $('drawer').classList.remove('open'); $('shade').classList.remove('show') }
function bind(){document.addEventListener('click',e=>{const j=e.target.closest('[data-jump]');if(j){S.idx=+j.dataset.jump;closeDrawer();render()}const r=e.target.closest('[data-review]');if(r){const id=r.dataset.review;S.mode='due';S.filtered=dueItems();S.idx=Math.max(0,S.filtered.findIndex(x=>x.id===id));closeDrawer();render()}});$('toolsBtn').onclick=openDrawer;$('closeDrawer').onclick=closeDrawer;$('shade').onclick=closeDrawer;$('prevBtn').onclick=()=>{S.idx=Math.max(0,S.idx-1);render()};$('nextBtn').onclick=()=>{S.idx=Math.min(S.filtered.length-1,S.idx+1);render()};$('learnBtn').onclick=markLearn;$('speakBtn').onclick=()=>speak(current().sentence);$('searchInput').oninput=()=>{S.mode='all';renderList()};$('allListBtn').onclick=()=>{S.mode='all';S.idx=0;renderList()};$('todayListBtn').onclick=()=>{S.mode='due';S.idx=0;renderList()};$('backupBtn').onclick=backup;document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('extractBtn').onclick=extractSentences;$('dictSearch').oninput=dictSearch;$('pronSpeak').onclick=()=>speak($('pronInput').value||current().sentence)}
function tab(name){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.id==='tab-'+name));if(name==='review')renderReview()}
function extractSentences(){const text=$('miningText').value;const s=text.match(/[^.!?]+[.!?]+/g)||[];$('miningResults').innerHTML=s.map((v,i)=>`<div class="item"><b>${esc(v.trim())}</b><small>Metinden çıkarıldı</small></div>`).join('')||'<p class="muted">Cümle bulunamadı.</p>'}
function dictSearch(){const q=norm($('dictSearch').value);if(!q){$('dictResults').innerHTML='';return}let out=[];if(Array.isArray(S.dict))out=out.concat(S.dict.filter(x=>norm(x.Kelime||x.word).includes(q)).slice(0,20).map(x=>({w:x.Kelime||x.word,m:[x.anlam1,x.anlam2,x.anlam3].filter(Boolean).join(' / ')||((x.meanings||[]).join(' / ')),p:x.türkçe_okunuş||'',l:x.seviye||'',z:x.zipf||''})));if(Array.isArray(S.broad)&&out.length<20)out=out.concat(S.broad.filter(x=>norm(x.word).includes(q)).slice(0,20-out.length).map(x=>({w:x.word,m:(x.meanings||[]).join(' / ')})));$('dictResults').innerHTML=out.map(x=>`<div class="dict-card"><b>${esc(x.w)}</b><br>${esc(x.m||'Anlam yok')}<br><small>${esc([x.p,x.l,x.z].filter(Boolean).join(' • '))}</small></div>`).join('')||'<p class="muted">Sonuç yok.</p>'}
function backup(){const blob=new Blob([JSON.stringify({learned:S.learned,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dil-haritasi-yedek-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)}
window.addEventListener('DOMContentLoaded',init);
})();
