/* ai-choice.js — kullanicinin AI erisim tercihi (API anahtari / Gemini web) */
(function(global){"use strict";if(global.DHAIChoice)return;
function profile(){try{return JSON.parse(localStorage.getItem("dh-profile-v1")||"{}")||{};}catch(e){return {};}}
function save(mode){var p=profile();p.aiYontemi=mode;p.aiYontemiTarih=Date.now();try{localStorage.setItem("dh-profile-v1",JSON.stringify(p));}catch(e){}try{global.dispatchEvent(new CustomEvent("dh-profile-changed",{detail:{aiYontemi:mode}}));}catch(e){}return p;}
function css(){if(document.getElementById("dh-ai-choice-css"))return;var s=document.createElement("style");s.id="dh-ai-choice-css";s.textContent=".dhaic-ov{position:fixed;inset:0;z-index:2147483600;background:rgba(2,6,23,.86);display:flex;align-items:center;justify-content:center;padding:16px}.dhaic-card{width:min(520px,100%);background:#0d1b32;color:#e8eef7;border:1px solid #334b70;border-radius:20px;padding:20px;font-family:Nunito,system-ui;box-shadow:0 24px 70px #000a}.dhaic-card h2{margin:0 0 8px}.dhaic-card p{color:#a9bad6;line-height:1.5}.dhaic-opt{display:block;width:100%;text-align:left;margin:10px 0;padding:15px;border-radius:14px;border:1px solid #31517e;background:#102542;color:#fff;font-weight:900;font-size:15px}.dhaic-opt small{display:block;color:#9fb3d9;font-weight:600;margin-top:5px;line-height:1.4}.dhaic-key{display:none;margin-top:12px}.dhaic-key input{width:100%;box-sizing:border-box;padding:13px;border-radius:11px;border:1px solid #31517e;background:#071120;color:#fff}.dhaic-save{width:100%;margin-top:9px;padding:12px;border:0;border-radius:11px;background:#10b981;color:#fff;font-weight:900}";document.head.appendChild(s);}
function addKey(k){k=String(k||"").trim();if(!k)return false;var store=/^AIza/.test(k)?"geminiApiKeys":/^csk-/i.test(k)?"cerebrasApiKeys":"groqApiKeys";try{var a=JSON.parse(localStorage.getItem(store)||"[]")||[];if(a.indexOf(k)<0)a.push(k);localStorage.setItem(store,JSON.stringify(a));return true;}catch(e){return false;}}
function hasStoredKey(){try{return ["groqApiKeys","cerebrasApiKeys","geminiApiKeys"].some(function(k){return (JSON.parse(localStorage.getItem(k)||"[]")||[]).filter(Boolean).length;});}catch(e){return false;}}
function open(required){css();var old=document.querySelector(".dhaic-ov");if(old)return old;var ov=document.createElement("div");ov.className="dhaic-ov";ov.innerHTML='<div class="dhaic-card"><h2>Yapay zekâyı nasıl kullanacaksın?</h2><p>Bu tercih bütün programda geçerli olur ve daha sonra değiştirilebilir.</p><button class="dhaic-opt" data-mode="api">🔑 API anahtarım var<small>Yanıtlar program içinde otomatik gelir. Anahtar yalnız bu cihazda tutulur.</small></button><div class="dhaic-key"><input type="password" placeholder="Groq, Cerebras veya Gemini API anahtarı"><button class="dhaic-save">Anahtarı kaydet ve devam et</button></div><button class="dhaic-opt" data-mode="gemini">💎 Anahtar kullanmayacağım<small>Program promptu kopyalar, Gemini\'yi açar; yanıtı yapıştırınca işlev devam eder.</small></button></div>';document.body.appendChild(ov);var key=ov.querySelector(".dhaic-key"),inp=key.querySelector("input");ov.querySelector('[data-mode="api"]').onclick=function(){if(hasStoredKey()){save("api");ov.remove();return;}key.style.display="block";inp.focus();};key.querySelector("button").onclick=function(){if(!addKey(inp.value)){inp.focus();return;}save("api");ov.remove();};ov.querySelector('[data-mode="gemini"]').onclick=function(){save("gemini");ov.remove();};return ov;}
function ensure(){var p=profile();if(!p.aiYontemi)open(true);}
global.DHAIChoice={open:open,ensure:ensure,get:function(){return profile().aiYontemi||"";},set:save};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",ensure);else ensure();
})(window);
