/* Atlas motion/components layer for the existing multi-page Dil Harita app. */
(function(g){"use strict";if(g.DHAtlasFX)return;
var doc=document,raf=0,reduce=matchMedia&&matchMedia("(prefers-reduced-motion: reduce)").matches;
function el(tag,cls){var x=doc.createElement(tag);if(cls)x.className=cls;return x}
function setting(k,v){try{if(v===undefined)return localStorage.getItem(k);localStorage.setItem(k,v)}catch(e){return null}}
function applyPrefs(){var theme=setting("dh-atlas-theme")||"dark",reading=setting("dh-atlas-reading")==="1";doc.documentElement.dataset.atlasTheme=theme;doc.documentElement.dataset.atlasReading=String(reading)}
function scene(){if(doc.getElementById("atlas-aurora"))return;var a=el("div");a.id="atlas-aurora";a.setAttribute("aria-hidden","true");a.innerHTML="<i></i><i></i><i></i>";doc.body.prepend(a);var s=el("canvas");s.id="atlas-stars";s.setAttribute("aria-hidden","true");doc.body.appendChild(s);var c=el("canvas");c.id="atlas-confetti";c.setAttribute("aria-hidden","true");doc.body.appendChild(c);if(!reduce)stars(s)}
function stars(c){var x=c.getContext("2d"),dpr=Math.min(devicePixelRatio||1,2),p=[];function size(){c.width=innerWidth*dpr;c.height=innerHeight*dpr;c.style.width=innerWidth+"px";c.style.height=innerHeight+"px";x.setTransform(dpr,0,0,dpr,0,0);p=Array.from({length:Math.min(130,Math.round(innerWidth/9))},function(){return{x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.35+Math.random()*1.15,v:.05+Math.random()*.22,o:.15+Math.random()*.65}})}function draw(){x.clearRect(0,0,innerWidth,innerHeight);x.fillStyle=getComputedStyle(doc.documentElement).getPropertyValue("--atlas-text")||"#fff";p.forEach(function(q){q.y+=q.v;if(q.y>innerHeight+2){q.y=-2;q.x=Math.random()*innerWidth}x.globalAlpha=q.o*(.7+.3*Math.sin((q.y+Date.now()/40)*.025));x.beginPath();x.arc(q.x,q.y,q.r,0,Math.PI*2);x.fill()});raf=requestAnimationFrame(draw)}size();addEventListener("resize",size,{passive:true});draw()}
function controls(){if(doc.querySelector(".atlas-controls"))return;var box=el("div","atlas-controls"),theme=el("button"),read=el("button");theme.type=read.type="button";theme.title="Gece / ışık teması";theme.setAttribute("aria-label",theme.title);read.title="Okuma kolaylığı";read.setAttribute("aria-label",read.title);function paint(){theme.textContent=doc.documentElement.dataset.atlasTheme==="light"?"☀":"◐";read.textContent="Aa";read.setAttribute("aria-pressed",doc.documentElement.dataset.atlasReading==="true")}theme.onclick=function(){var v=doc.documentElement.dataset.atlasTheme==="light"?"dark":"light";setting("dh-atlas-theme",v);applyPrefs();paint()};read.onclick=function(){setting("dh-atlas-reading",doc.documentElement.dataset.atlasReading==="true"?"0":"1");applyPrefs();paint()};box.append(theme,read);doc.body.appendChild(box);paint()}
function confetti(n){if(reduce)return;var c=doc.getElementById("atlas-confetti");if(!c)return;var x=c.getContext("2d"),colors=["#7c5cff","#22d3ee","#ff5ca8","#34e2a0","#ffd76e"],p=Array.from({length:n||90},function(){return{x:Math.random()*innerWidth,y:-20-Math.random()*innerHeight*.35,w:5+Math.random()*7,h:8+Math.random()*10,vy:1.8+Math.random()*3.5,vx:(Math.random()-.5)*2,a:Math.random()*6,va:(Math.random()-.5)*.25,c:colors[Math.random()*colors.length|0]}});c.width=innerWidth;c.height=innerHeight;var f=0;(function draw(){x.clearRect(0,0,c.width,c.height);p.forEach(function(q){q.y+=q.vy;q.x+=q.vx;q.a+=q.va;x.save();x.translate(q.x,q.y);x.rotate(q.a);x.fillStyle=q.c;x.fillRect(-q.w/2,-q.h/2,q.w,q.h);x.restore()});if(++f<420&&p.some(function(q){return q.y<innerHeight+30}))requestAnimationFrame(draw);else x.clearRect(0,0,c.width,c.height)})()}
function ring(percent,label){var n=Math.max(0,Math.min(100,Number(percent)||0)),r=45,c=2*Math.PI*r,w=el("div","atlas-ring");w.innerHTML='<svg viewBox="0 0 110 110" aria-hidden="true"><defs><linearGradient id="atlas-ring-gradient"><stop stop-color="#7c5cff"/><stop offset="1" stop-color="#22d3ee"/></linearGradient></defs><circle class="track" cx="55" cy="55" r="45"/><circle class="value" cx="55" cy="55" r="45" stroke-dasharray="'+c+'" stroke-dashoffset="'+c+'"/></svg><strong>'+Math.round(n)+'%'+(label?'<small style="display:block;font-size:9px;color:var(--atlas-muted)">'+label+'</small>':'')+'</strong>';setTimeout(function(){var q=w.querySelector(".value");if(q)q.style.strokeDashoffset=c*(1-n/100)},50);return w}
function wave(target,on){if(!target)return;var old=target.querySelector(".atlas-wave");if(old)old.remove();if(!on)return;var w=el("div","atlas-wave");for(var i=0;i<15;i++){var b=el("i");b.style.setProperty("--n",i);w.appendChild(b)}target.appendChild(w)}
function flipWords(){doc.addEventListener("click",function(e){var b=e.target.closest&&e.target.closest("#revealBtn,.reveal-btn");if(!b)return;var card=b.closest(".card");if(card){card.classList.add("atlas-flip","is-flipping");setTimeout(function(){card.classList.remove("is-flipping")},750)}},true)}
function micWave(){function bind(b){if(!b||b.__atlasWave)return;b.__atlasWave=1;var paint=function(){wave(b.parentElement||doc.body,b.classList.contains("listening")||b.classList.contains("active")||b.getAttribute("aria-pressed")==="true")};new MutationObserver(paint).observe(b,{attributes:true,attributeFilter:["class","aria-pressed"]})}doc.querySelectorAll("#micBtn,.mic-btn,[data-mic]").forEach(bind);new MutationObserver(function(){doc.querySelectorAll("#micBtn,.mic-btn,[data-mic]").forEach(bind)}).observe(doc.body,{childList:true,subtree:true});g.addEventListener("dh-speech-start",function(){var im=doc.querySelector("#avatarImg,.avatar img,.avatar-stage img");if(im)im.classList.add("atlas-avatar-speaking")});g.addEventListener("dh-speech-end",function(){var im=doc.querySelector("#avatarImg,.avatar img,.avatar-stage img");if(im)im.classList.remove("atlas-avatar-speaking")})}
function journeyRing(){if(!/^ogrenme-yolu\.html?$/i.test(location.pathname.split("/").pop()||""))return;var pct=doc.getElementById("totalPct"),head=doc.querySelector(".select");if(!pct||!head)return;var n=parseInt(pct.textContent,10)||0,r=ring(n,"tamam");r.style.marginLeft="auto";head.style.display="flex";head.style.alignItems="center";head.appendChild(r)}
function heatAndChart(){if(!/^(rapor|ilerleme)\.html?$/i.test(location.pathname.split("/").pop()||""))return;var host=doc.querySelector("main,.wrap,.container")||doc.body,card=el("section","card atlas-analytics");card.innerHTML="<h2>10 haftalık çalışma ritmi</h2>";var heat=el("div","atlas-heatmap"),tr={};try{tr=JSON.parse(localStorage.getItem("dh-study-tracker-v1")||"{}")||{}}catch(e){}var vals=[];for(var i=69;i>=0;i--){var d=new Date();d.setDate(d.getDate()-i);var key=d.toISOString().slice(0,10),v=(tr.days&&tr.days[key])||{},n=(v.lessons||0)+(v.sentences||0)/5+(v.reviews||0)/3;vals.push(n);var q=el("i",n>9?"s4":n>5?"s3":n>1?"s2":n>0?"s1":"");q.title=key+" · "+Math.round(n)+" etkinlik";heat.appendChild(q)}card.appendChild(heat);var data=vals.slice(-30),mx=Math.max.apply(null,data.concat([1])),pts=data.map(function(v,i){return[(i/(data.length-1)*296+2).toFixed(1),(96-v/mx*86).toFixed(1)]}),path=pts.map(function(p,i){return(i?"L":"M")+p[0]+" "+p[1]}).join(" ");var svg=doc.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("class","atlas-chart");svg.setAttribute("viewBox","0 0 300 100");svg.innerHTML='<defs><linearGradient id="atlas-chart-fill" x2="0" y2="1"><stop stop-color="#22d3ee"/><stop offset="1" stop-color="#7c5cff" stop-opacity="0"/></linearGradient></defs><path class="area" d="'+path+' L298 100 L2 100 Z"/><path class="line" d="'+path+'" vector-effect="non-scaling-stroke"/>';card.appendChild(svg);host.appendChild(card)}
function start(){applyPrefs();scene();controls();flipWords();micWave();journeyRing();heatAndChart();g.addEventListener("dh-session-completed",function(){confetti(110)});var mo=new MutationObserver(function(ms){ms.forEach(function(m){m.addedNodes.forEach(function(n){if(n.nodeType===1&&(/tamam|tebrik/i.test(n.textContent||"")))confetti(80)})})});mo.observe(doc.body,{childList:true,subtree:true})}
g.DHAtlasFX={confetti:confetti,ring:ring,wave:wave};if(doc.readyState==="loading")doc.addEventListener("DOMContentLoaded",start,{once:true});else start()
})(window);
