(function(g){"use strict";if(g.DHBulkAI)return;
function show(title,text){if(g.DHGeminiQuality&&DHGeminiQuality._modal)return DHGeminiQuality._modal(title,text);alert(title+"\n\n"+text);}
function ask(title,sys,data,type){if(!(g.DHProviders&&DHProviders.hasAnyKey&&DHProviders.hasAnyKey()))return Promise.reject(new Error("AI yöntemi etkin değil"));return DHProviders.chat([{role:"system",content:sys},{role:"user",content:JSON.stringify(data)}],{temperature:.25,max_tokens:Math.max(1800,JSON.stringify(data).length/3),title:title,cacheType:type,cacheInput:data}).then(function(t){show(title,t);return t;});}
async function moduleSentences(){if(g.dhIndexActiveModuleSentences)return dhIndexActiveModuleSentences();var n=(document.querySelector(".study-title")||{}).textContent||"",all=[];try{var r=await fetch("./data/sentences.json");if(r.ok)all=await r.json();}catch(e){}var k=n.toLowerCase().replace(/\s+/g," ").trim();return all.filter(function(s){var m=String(s.module||"").toLowerCase().replace(/\s+/g," ").trim();return m===k||(k&&m.indexOf(k)===0)||(m&&k.indexOf(m)===0);});}
async function moduleWords(){var s=await moduleSentences(),set={},cache={};s.forEach(function(x){(String(x.en||"").toLowerCase().match(/[a-z]+(?:'[a-z]+)?/g)||[]).forEach(function(w){if(w.length>1)set[w]=1;});});try{cache=JSON.parse(localStorage.getItem("dh-word-package-v2")||"{}")||{};}catch(e){}var miss=Object.keys(set).filter(function(w){return !(cache[w]&&cache[w].data);});if(!miss.length)return show("♻️ Modül kelimeleri hazır","Bütün kelimeler daha önce açıklandı; AI’ye yeniden gönderilmedi.");var sys='Her İngilizce kelime için yalnız JSON dizi döndür: [{"word":"...","tanim":"Türkçe tanım","kullanim":"kullanım","telaffuz":"ipucu","esAnlamlilar":[],"kaliplar":[],"ornekler":[{"en":"...","tr":"..."}],"ipucu":"..."}]. Hiçbir kelimeyi atlama.';var raw=await DHProviders.chat([{role:"system",content:sys},{role:"user",content:JSON.stringify(miss)}],{json:true,title:"💎 Modül kelimelerini toplu açıkla",cacheType:"bulk-module-words",cacheInput:miss,max_tokens:Math.max(2200,miss.length*180)}),t=String(raw).replace(/```json|```/gi,""),rows=JSON.parse(t.slice(t.indexOf("["),t.lastIndexOf("]")+1)),saved=0;rows.forEach(function(p){var w=String(p.word||"").toLowerCase();if(set[w]&&p.tanim){cache[w]={at:Date.now(),data:p};saved++;}});localStorage.setItem("dh-word-package-v2",JSON.stringify(cache));show("✅ Modül kelimeleri",saved+" kelime paketi kaydedildi. Eksik kalırsa sonraki çalışmada yalnız eksikler gönderilir.");}
async function moduleReport(){var s=await moduleSentences();return ask("💎 Modül sonu öğretmen raporu","Bütün modül cümlelerinden Türkçe öğretmen raporu hazırla: kazanılan gramer ve kalıplar, karışabilecek noktalar, tekrar öncelikleri, üretim görevi ve kısa test. Hiçbir cümleyi atlama, veri uydurma.",{sentences:s},"bulk-module-report");}
async function errorLesson(){var r=[];if(g.LearningErrorDB&&LearningErrorDB.all)r=await LearningErrorDB.all();if(!r.length)throw new Error("Hata kaydı yok");return ask("💎 Hata Defteri toplu ders paketi","Bütün hataları ortak nedenlerine göre grupla. Her grup için kısa Türkçe ders, doğru kural, düzeltilmiş örnekler ve iki mini alıştırma ver. Doğru alternatifleri hata sayma.",{records:r},"bulk-error-lesson");}
async function combined(){if(!g.DHDailyPdf)throw new Error("Günlük veri hattı yok");var d=new Date(),key=d.toISOString().slice(0,10),r=await DHDailyPdf._recordsToday(key),ids=[],words=[];r.forEach(function(x){var k=String(x.key);if(k.indexOf("srs:")===0)ids.push(k.slice(4));else if(k.indexOf("wsrs:")===0)words.push(k.slice(5));});var studied=await DHDailyPdf._sentenceDetails(ids);d.setDate(d.getDate()+1);var end=new Date(d);end.setHours(23,59,59,999);var dueR=await DHDailyPdf._recordsDue(end.getTime()),p=DHDailyPdf._split(dueR),due=await DHDailyPdf._sentenceDetails(p.sentenceIds),mod=await DHDailyPdf._nextModule(),fresh=await DHDailyPdf._moduleSentences(mod);return ask("💎 Bugün + yarın çalışma paketi","Tek Türkçe raporda bugünün 3 kazanımını ve karışan noktaları değerlendir; sonra yalnız verilen malzemeyle yarının ısınma, tekrar, yeni çalışma ve üretim planını süreleriyle yaz.",{today:key,studied:studied,words:words,tomorrow:d.toISOString().slice(0,10),due:due,dueWords:p.words,module:mod,newSentences:fresh},"bulk-day-tomorrow");}
function btn(label,fn){var b=document.createElement("button");b.type="button";b.className="dh-pbtn dh-btn btn";b.textContent=label;b.onclick=function(){Promise.resolve(fn()).catch(function(e){if(!(e&&e.code==="abort"))alert("Toplu AI işlemi tamamlanamadı.");});};return b;}
function mount(){var page=(location.pathname.split("/").pop()||"").toLowerCase();if(page==="index-app.html"){var box=document.getElementById("dhToolsBox");if(!box)return setTimeout(mount,600);if(box.dataset.bulkAi)return;box.dataset.bulkAi="1";box.append(btn("💎 Modülün tüm kelimelerini açıkla",moduleWords),btn("💎 Modül sonu öğretmen raporu",moduleReport),btn("💎 PDF için eksik açıklamaları tamamla",function(){return g.prepareModulePdfWithAI?prepareModulePdfWithAI():g.explainActiveModuleWithAI&&explainActiveModuleWithAI();}));}else if(page==="hata-defteri.html"){var a=document.getElementById("aiCleanBtn");if(a&&!document.getElementById("bulkErrorLesson")){var b=btn("💎 Toplu AI ders paketi",errorLesson);b.id="bulkErrorLesson";a.insertAdjacentElement("afterend",b);}}else if(page==="index.html"){var y=document.getElementById("yarinGemini");if(y&&!document.getElementById("bulkDayPlan")){var c=btn("💎 Bugün + yarın tek Gemini paketi",combined);c.id="bulkDayPlan";y.insertAdjacentElement("afterend",c);}}}
g.DHBulkAI={moduleWords:moduleWords,moduleReport:moduleReport,errorLesson:errorLesson,combinedDayPlan:combined};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount);else mount();})(window);
