/* immersive.js — İngilizceyi Yaşa: bağımsız yaşam senaryosu */
(function(global){
"use strict";
var KEY="dh-immersive-state-v1", SOUND_KEY="dh-immersive-sound-v1";
var SCENES=[
 {id:"hotel",videoQuery:["luxury hotel lobby reception guests","boutique hotel front desk"],title:"The Lost Reservation",place:"LONDON · BOUTIQUE HOTEL",level:"A2",role:"hotel receptionist",name:"Daniel",image:"./assets/avatars_v3/hotel/idle.webp",mission:"Find your missing reservation and check in before the hotel closes.",opener:"Good evening. Welcome to the Riverside Hotel. May I have your name, please?",hint:"Try: “Hi, I have a reservation under the name …”",quick:["I have a reservation.","Could you check again, please?","What information do you need?"]},
 {id:"restaurant",videoQuery:["modern restaurant dining room people","restaurant waiter dining service"],title:"A Table with a Problem",place:"MANCHESTER · CITY RESTAURANT",level:"A2",role:"restaurant waiter",name:"James",image:"./assets/avatars_v3/restaurant/idle.webp",mission:"Order dinner, explain a food restriction and solve a problem with your meal.",opener:"Good evening! Welcome. Are you ready to order, or would you like a few more minutes?",hint:"Try: “Could you recommend something without …?”",quick:["Could I see the menu, please?","What do you recommend?","I can't eat dairy products."]},
 {id:"airport",videoQuery:["airport check in counter travelers","airport terminal departure hall"],title:"The Last Boarding Call",place:"HEATHROW · TERMINAL 5",level:"A2–B1",role:"airport check-in agent",name:"Alex",image:"./assets/avatars_v3/airport/idle.webp",mission:"Check in, handle a baggage issue and reach the correct gate on time.",opener:"Good morning. Where are you flying today?",hint:"Try: “I'm flying to …, but I have a problem with my luggage.”",quick:["I'm flying to New York.","Can I check in this bag?","Which gate should I go to?"]},
 {id:"doctor",videoQuery:["medical clinic reception waiting room","doctor office modern clinic"],title:"An Unexpected Appointment",place:"BRISTOL · HEALTH CLINIC",level:"B1",role:"doctor",name:"Dr. Thomas",image:"./assets/avatars_v3/doctor/idle.webp",mission:"Describe how you feel, answer the doctor's questions and understand the advice.",opener:"Hello. Please take a seat. What seems to be the problem today?",hint:"Try: “I've been feeling … since …”",quick:["I've had a headache since yesterday.","It gets worse in the evening.","What should I do?"]}
];
var state={sceneId:"",messages:[],turns:0,corrections:0,progress:8,updatedAt:0,completed:false},scene=null,lastReply="",busy=false,recognition=null,videoRun=0;
var lip={frames:null,seq:[],charAt:[],timer:null,endTimer:null,blinkTimer:null,index:0,speaking:false,run:0};
function $(id){return document.getElementById(id)}
function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function todayIndex(){var d=new Date(),stamp=Date.UTC(d.getFullYear(),d.getMonth(),d.getDate());return Math.floor(stamp/86400000)%SCENES.length}
function read(){try{var v=JSON.parse(localStorage.getItem(KEY)||"null");if(v&&typeof v==="object")state=Object.assign(state,v)}catch(e){}repairSavedMessages()}
function save(){state.updatedAt=Date.now();try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}try{global.dispatchEvent(new CustomEvent("dh-immersive-changed",{detail:{updatedAt:state.updatedAt}}))}catch(e){}}
function soundOn(){return localStorage.getItem(SOUND_KEY)!=="0"}
function source(info){if(!info)return;var el=$("sourceLabel");el.hidden=false;el.textContent="AI kaynağı: "+(info.label||info.provider||"AI")+" · "+(info.model||"Model belirtilmedi")+(info.cached?" · önbellekten":"")}
function avatarFrames(s){var base=String(s&&s.image||"").replace(/idle\.webp(?:\?.*)?$/i,"");return{idle:base+"idle.webp",blink:base+"blink.webp",listen:base+"listen.webp",a:base+"mouth-a.webp",e:base+"mouth-e.webp",i:base+"mouth-i.webp",o:base+"mouth-o.webp",u:base+"mouth-u.webp",mbp:base+"mouth-mbp.webp",fv:base+"mouth-fv.webp",l:base+"mouth-l.webp",th:base+"mouth-th.webp"}}
function showAvatar(src){var img=$("characterImage");if(img&&src&&img.src!==new URL(src,location.href).href)img.src=src}
function scheduleBlink(){clearTimeout(lip.blinkTimer);lip.blinkTimer=setTimeout(function(){if(lip.speaking){scheduleBlink();return}showAvatar(lip.frames&&lip.frames.blink);setTimeout(function(){if(!lip.speaking)showAvatar(lip.frames&&lip.frames.idle);scheduleBlink()},280)},2200+Math.random()*2200)}
function prepareAvatar(s){stopMouth();lip.frames=avatarFrames(s);Object.keys(lip.frames).forEach(function(k){var im=new Image();im.src=lip.frames[k]});showAvatar(lip.frames.idle);scheduleBlink()}
function stopSceneVideo(){videoRun++;var v=$("sceneVideo"),bg=$("sceneVideoBg");if(bg)bg.classList.remove("is-ready");if(v){try{v.pause()}catch(e){}v.removeAttribute("src");v.removeAttribute("poster");v.load()}var label=$("liveSceneLabel");if(label)label.textContent="CANLI SAHNE"}
function loadSceneVideo(s){stopSceneVideo();var run=videoRun,v=$("sceneVideo"),bg=$("sceneVideoBg"),label=$("liveSceneLabel");if(!v||!bg||!global.DHOrtamFon||!DHOrtamFon.sahneVideosu)return;DHOrtamFon.sahneVideosu({id:s.id,sorgular:s.videoQuery||[]}).then(function(f){if(run!==videoRun||!f||f.tur!=="video"||!f.url)return;if(f.poster)v.poster=f.poster;v.src=f.url;v.muted=true;v.defaultMuted=true;v.loop=true;v.playsInline=true;var ready=function(){if(run!==videoRun)return;bg.classList.add("is-ready");if(label)label.textContent="CANLI ORTAM"};v.addEventListener("loadeddata",ready,{once:true});v.addEventListener("error",function(){if(run===videoRun)stopSceneVideo()},{once:true});v.load();try{var play=v.play();if(play&&play.catch)play.catch(function(){})}catch(e){}}).catch(function(){})}
function startMouth(text,duration,run){if(run!==lip.run||!lip.frames)return;clearInterval(lip.timer);clearTimeout(lip.endTimer);lip.speaking=true;lip.index=0;var map={a:lip.frames.a,e:lip.frames.e,i:lip.frames.i,o:lip.frames.o,u:lip.frames.u,mbp:lip.frames.mbp,fv:lip.frames.fv,l:lip.frames.l,th:lip.frames.th,idle:lip.frames.idle};var tl=global.DHViseme&&DHViseme.timeline?DHViseme.timeline(text,map,"en"):null;lip.seq=tl&&tl.frames&&tl.frames.length?tl.frames:[lip.frames.i,lip.frames.e,lip.frames.a,lip.frames.o,lip.frames.u,lip.frames.mbp,lip.frames.idle];lip.charAt=tl&&tl.charAt||[];var step=Math.max(40,Math.min(170,Math.round(duration/Math.max(1,lip.seq.length))));showAvatar(lip.seq[0]);lip.timer=setInterval(function(){if(run!==lip.run)return;if(lip.index>=lip.seq.length){showAvatar(lip.frames.idle);return}showAvatar(lip.seq[lip.index++])},step);lip.endTimer=setTimeout(function(){stopMouth(run)},duration+250)}
function alignMouth(charIndex,run){if(run!==lip.run||!lip.charAt.length||!global.DHViseme||!DHViseme.indexForChar)return;var at=DHViseme.indexForChar(lip.charAt,charIndex);if(Math.abs(at-lip.index)>2)lip.index=at}
function stopMouth(run){if(run!=null&&run!==lip.run)return;clearInterval(lip.timer);clearTimeout(lip.endTimer);lip.speaking=false;lip.seq=[];lip.charAt=[];var img=$("characterImage");if(img)img.classList.remove("is-speaking");if(lip.frames){showAvatar(lip.frames.listen);setTimeout(function(){if(!lip.speaking)showAvatar(lip.frames.idle)},220)}}
function speak(text){if(!soundOn()||!("speechSynthesis" in global)||!text)return;try{var spoken=String(text).replace(/[*_#]/g,""),run=++lip.run;speechSynthesis.cancel();stopMouth(run);var u=new SpeechSynthesisUtterance(spoken),duration=Math.max(1200,Math.min(12000,spoken.length*82));u.lang="en-GB";u.rate=.92;u.onstart=function(){if(run!==lip.run)return;$("characterImage").classList.add("is-speaking");startMouth(spoken,duration,run)};u.onboundary=function(ev){if(typeof ev.charIndex==="number")alignMouth(ev.charIndex,run)};u.onend=u.onerror=function(){if(run!==lip.run)return;stopMouth(run);scheduleBlink()};speechSynthesis.speak(u)}catch(e){stopMouth()}}
function renderCards(){var daily=todayIndex();$("dailyMission").innerHTML="Bugün önerilen dünya<strong>"+esc(SCENES[daily].title)+" · "+esc(SCENES[daily].mission)+"</strong>";$("sceneCards").innerHTML=SCENES.map(function(s,i){return '<button class="imm-card'+(i===daily?' is-daily':'')+'" type="button" data-scene="'+s.id+'"><img src="'+s.image+'" alt="" loading="lazy"><span class="imm-card-content"><small>'+esc(s.place.split(" · ")[0])+' · '+esc(s.level)+'</small><b>'+esc(s.title)+'</b><span>'+esc(s.mission)+'</span></span></button>'}).join("");Array.prototype.forEach.call(document.querySelectorAll("[data-scene]"),function(b){b.onclick=function(){startScene(b.getAttribute("data-scene"))}})}
function setView(which){$("scenePicker").hidden=which!=="picker";$("world").hidden=which!=="world";$("summary").hidden=which!=="summary"}
function findScene(id){return SCENES.filter(function(s){return s.id===id})[0]||SCENES[todayIndex()]}
function startScene(id,keep){scene=findScene(id);if(!keep||state.sceneId!==scene.id||state.completed){state={sceneId:scene.id,messages:[{role:"assistant",content:scene.opener}],turns:0,corrections:0,progress:8,updatedAt:Date.now(),completed:false};save()}scene=findScene(state.sceneId);$("sceneLevel").textContent=scene.level;prepareAvatar(scene);loadSceneVideo(scene);$("characterImage").alt=scene.name+", "+scene.role;$("scenePlace").textContent=scene.place;$("sceneTitle").textContent=scene.title;$("missionText").textContent=scene.mission;renderMessages();renderQuick(scene.quick);updateProgress();setView("world");lastReply=(state.messages.filter(function(m){return m.role==="assistant"}).slice(-1)[0]||{}).content||scene.opener;setTimeout(function(){speak(lastReply)},250)}
function renderMessages(){var box=$("dialogue");box.innerHTML=state.messages.map(function(m){var user=m.role==="user";return '<div class="imm-msg '+(user?'user':'guide')+'"><div><div class="imm-msg-name">'+(user?'YOU':esc(scene.name.toUpperCase()))+'</div><div class="imm-msg-bubble">'+esc(m.content)+(m.correction?'<div class="imm-correction">💡 '+esc(m.correction)+'</div>':'')+'</div></div></div>'}).join("");box.scrollTop=box.scrollHeight}
function renderQuick(items){$("quickReplies").innerHTML=(items||[]).slice(0,3).map(function(x){return '<button type="button">'+esc(x)+'</button>'}).join("");Array.prototype.forEach.call($("quickReplies").querySelectorAll("button"),function(b){b.onclick=function(){$("userMessage").value=b.textContent;autoSize();$("userMessage").focus()}})}
function updateProgress(){$("missionBar").style.width=Math.max(8,Math.min(100,state.progress||8))+"%"}
function typing(on){var old=$("typingMessage");if(old)old.remove();if(!on)return;var d=document.createElement("div");d.id="typingMessage";d.className="imm-msg guide";d.innerHTML='<div><div class="imm-msg-name">'+esc(scene.name.toUpperCase())+'</div><div class="imm-msg-bubble"><span class="imm-typing"><i></i><i></i><i></i></span></div></div>';$("dialogue").appendChild(d);$("dialogue").scrollTop=$("dialogue").scrollHeight}
function cleanAIText(raw){return String(raw||"").trim().replace(/^DH-ID:[^\r\n]*(?:\r?\n)?/i,"").replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim()}
function repairJsonControls(text){var out="",quoted=false,escaped=false;for(var i=0;i<text.length;i++){var c=text.charAt(i);if(quoted&&(c==="\n"||c==="\r"||c==="\t")){out+=" ";continue}out+=c;if(c==='"'&&!escaped)quoted=!quoted;escaped=c==="\\"&&!escaped;if(c!=="\\")escaped=false}return out.replace(/,\s*([}\]])/g,"$1")}
function decodeField(text,key){var m=new RegExp('"'+key+'"\\s*:\\s*"((?:\\\\.|[^"\\\\])*)"',"i").exec(text);if(!m)return "";try{return JSON.parse('"'+m[1]+'"')}catch(e){return m[1].replace(/\\n/g," ").replace(/\\"/g,'"').replace(/\\\\/g,"\\")}}
function decodeLooseField(text,key){var standard=decodeField(text,key);if(standard)return standard;var smart=new RegExp('[“”]'+key+'[“”]\\s*:\\s*[“”]([\\s\\S]*?)[“”](?=\\s*(?:,|[}]))',"i").exec(text);if(smart)return smart[1].trim();var single=new RegExp("'"+key+"'\\s*:\\s*'([^']*)'","i").exec(text);return single?single[1].trim():""}
function normalizeReply(o){o=o&&typeof o==="object"?o:{};var q=Array.isArray(o.quick)?o.quick.filter(function(x){return typeof x==="string"&&x.trim()}).slice(0,3):[];return{reply:String(o.reply||"").trim(),correction:o.correction&&typeof o.correction==="object"?o.correction:null,progress:isFinite(+o.progress)?+o.progress:Math.min(95,(state.progress||8)+12),quick:q,missionComplete:o.missionComplete===true}}
function parseReply(raw){var t=cleanAIText(raw),candidate=t;if(/\\"reply\\"\s*:/.test(candidate))candidate=candidate.replace(/\\"/g,'"').replace(/\\n/g," ");var a=candidate.indexOf("{"),b=candidate.lastIndexOf("}");if(a>=0&&b>a)candidate=candidate.slice(a,b+1);for(var pass=0;pass<3;pass++){try{var parsed=JSON.parse(repairJsonControls(candidate));if(typeof parsed==="string"){candidate=cleanAIText(parsed);continue}var ready=normalizeReply(parsed);if(ready.reply)return ready}catch(e){}break}var reply=decodeLooseField(candidate,"reply");if(reply){var original=decodeLooseField(candidate,"original"),better=decodeLooseField(candidate,"better"),note=decodeLooseField(candidate,"noteTR"),pm=/["“”]?progress["“”]?\s*:\s*(\d+)/i.exec(candidate),done=/["“”]?missionComplete["“”]?\s*:\s*true/i.test(candidate);return{reply:reply,correction:original&&better?{original:original,better:better,noteTR:note}:null,progress:pm?+pm[1]:Math.min(95,(state.progress||8)+12),quick:[],missionComplete:done}}if(/^\s*[{[]/.test(t)||/["“”\\]reply["“”\\]\s*:/.test(t))return{reply:"",correction:null,progress:Math.min(95,(state.progress||8)+8),quick:[],missionComplete:false,parseFailed:true};return{reply:t||"",correction:null,progress:Math.min(95,(state.progress||8)+12),quick:[],missionComplete:false,parseFailed:!t}}
function repairSavedMessages(){var changed=false,oldFallback=/^(?:I’m sorry, I didn’t catch that clearly\. Could you say it again\?|Could you say that again, please\?)$/;(state.messages||[]).forEach(function(m){if(!m||m.role!=="assistant"||typeof m.content!=="string")return;if(!/^\s*[{[]/.test(m.content)&&!/"reply"\s*:/.test(m.content))return;var fixed=parseReply(m.content);if(fixed.reply&&fixed.reply!==m.content){m.content=fixed.reply;if(fixed.correction&&fixed.correction.better)m.correction=fixed.correction.better+(fixed.correction.noteTR?" — "+fixed.correction.noteTR:"");changed=true}});var before=(state.messages||[]).length;state.messages=(state.messages||[]).filter(function(m){return !(m&&m.role==="assistant"&&oldFallback.test(String(m.content||"").trim()))});if(state.messages.length!==before)changed=true;if(changed){state.updatedAt=Date.now();try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}}
function historyPrompt(userText){var profile="";try{profile=global.DHProfile&&DHProfile.context?DHProfile.context():""}catch(e){}var history=state.messages.slice(-10).map(function(m){return(m.role==="user"?"LEARNER: ":scene.name.toUpperCase()+": ")+m.content}).join("\n");return[{role:"system",content:"Run an immersive English role-play. Stay strictly in character as a "+scene.role+" named "+scene.name+". Scenario: "+scene.title+". Mission: "+scene.mission+". Keep the story moving with one natural reply and usually one question. Match level "+scene.level+". Never switch to Turkish. Understand the learner's intended meaning even when grammar, spelling, capitalization, or word order is imperfect. Answer the meaning first; never claim you did not understand merely because the English has errors. Do not praise generically. If the learner made a meaningful English error, give one short correction; ignore harmless alternatives and typos. Return ONLY JSON: {\"reply\":\"English character reply\",\"correction\":null or {\"original\":\"exact learner phrase\",\"better\":\"correct English\",\"noteTR\":\"very short Turkish explanation\"},\"progress\":integer 0-100,\"quick\":[\"three short English reply ideas\"],\"missionComplete\":boolean}. "+profile},{role:"user",content:"Conversation so far:\n"+history+"\nLEARNER: "+userText+"\nInfer the intended meaning and continue the scene now."}]}
function plainRetryPrompt(userText){return[{role:"system",content:"You are "+scene.name+", a "+scene.role+" in the scenario "+scene.title+". Understand imperfect English charitably. Reply directly to the learner's intended meaning in one or two natural English sentences. Stay in character. Return plain text only: no JSON, labels, Markdown, correction, or explanation."},{role:"user",content:userText}]}
function callAI(messages,plain){if(!global.DHProviders)return Promise.reject({code:"missing"});var opt={temperature:.72,max_tokens:plain?180:450,json:!plain};if(DHProviders.mode&&DHProviders.mode()==="gemini")return DHProviders.chat(messages,opt);if(DHProviders.realHasAnyKey&&DHProviders.realHasAnyKey())return DHProviders.chat(messages,opt);return DHProviders.manualChat(messages,opt)}
async function parseOrRetry(raw,userText){var out=parseReply(raw);if(!out.parseFailed)return out;$("status").textContent="Yanıt biçimi düzeltiliyor…";var plain=await callAI(plainRetryPrompt(userText),true),fixed=parseReply(plain);if(!fixed.parseFailed&&fixed.reply)return fixed;return{reply:"I understand your question. Let me help you with that.",correction:null,progress:Math.min(95,(state.progress||8)+8),quick:scene.quick||[],missionComplete:false}}
async function recordCorrection(c,userText){if(!c||!c.better||!c.original||!global.LearningErrorDB)return;var original=String(c.original).trim();if(userText.toLowerCase().indexOf(original.toLowerCase())<0&&original.toLowerCase().indexOf(userText.toLowerCase())<0)return;try{var rec=await LearningErrorDB.add({target:c.better,answer:original,sentenceTR:c.noteTR||"Yaşam sahnesindeki ifade",module:"İngilizceyi Yaşa · "+scene.title,level:scene.level,source:"immersive",grade:"hard",score:0});if(rec)state.corrections=(state.corrections||0)+1}catch(e){}}
async function send(text){text=String(text||"").replace(/\s+/g," ").trim();if(!text||busy)return;busy=true;$("sendButton").disabled=true;$("userMessage").value="";autoSize();$("helpBox").hidden=true;state.messages.push({role:"user",content:text});state.turns=(state.turns||0)+1;renderMessages();typing(true);$("status").textContent="Sahnedeki karakter düşünüyor…";try{var raw=await callAI(historyPrompt(text));var out=await parseOrRetry(raw,text),corr=out.correction||null;typing(false);await recordCorrection(corr,text);var corrText=corr&&corr.better?(corr.better+(corr.noteTR?" — "+corr.noteTR:"")):"";lastReply=String(out.reply||"").trim()||"I understand. Let me help you with that.";state.messages.push({role:"assistant",content:lastReply,correction:corrText});state.progress=Math.max(state.progress||8,Math.min(100,+out.progress||((state.progress||8)+12)));save();renderMessages();renderQuick(Array.isArray(out.quick)&&out.quick.length?out.quick:scene.quick);updateProgress();source(DHProviders.lastResponseInfo);$("status").textContent=corrText?"Bir ifade hata defterine eklendi.":"Hikâye cevabına göre ilerledi.";speak(lastReply);if(out.missionComplete&&state.turns>=3)setTimeout(finish,900)}catch(e){typing(false);$("status").textContent=(e&&e.code==="abort")?"İstek durduruldu.":"Yanıt alınamadı. Bağlantını veya AI ayarını kontrol edip tekrar dene.";state.messages.pop();state.turns=Math.max(0,state.turns-1);renderMessages()}finally{busy=false;$("sendButton").disabled=false;$("userMessage").focus()}}
function finish(){if(busy)return;stopSceneVideo();state.completed=true;state.progress=100;save();try{global.dhBumpDailyTracker&&dhBumpDailyTracker("speaking");global.dhLogActivity&&dhLogActivity("🌍 İngilizceyi Yaşa sahnesi tamamlandı: "+scene.title,"speaking")}catch(e){}$("summaryTitle").textContent=scene.title;$("summaryText").textContent="Görevi İngilizce iletişim kurarak tamamladın. Anlamlı hataların hata defterinde; sonraki çalışmalarda yeniden karşına çıkacak.";$("turnCount").textContent=state.turns||0;$("correctionCount").textContent=state.corrections||0;setView("summary")}
function autoSize(){var t=$("userMessage");t.style.height="auto";t.style.height=Math.min(110,t.scrollHeight)+"px"}
function setupRecognition(){var R=global.SpeechRecognition||global.webkitSpeechRecognition;if(!R){$("micButton").hidden=true;return}recognition=new R();recognition.lang="en-GB";recognition.interimResults=true;recognition.continuous=false;recognition.onstart=function(){$("micButton").classList.add("is-listening");$("status").textContent="Dinliyorum… İngilizce konuş."};recognition.onresult=function(ev){var s="";for(var i=ev.resultIndex;i<ev.results.length;i++)s+=ev.results[i][0].transcript;$("userMessage").value=s;autoSize()};recognition.onend=function(){$("micButton").classList.remove("is-listening");$("status").textContent=$("userMessage").value?"Duyduğumu kontrol et ve gönder.":""};recognition.onerror=function(){$("micButton").classList.remove("is-listening");$("status").textContent="Mikrofon dinlemesi tamamlanamadı; yazarak devam edebilirsin."}}
function boot(){read();renderCards();$("soundToggle").textContent=soundOn()?"🔊":"🔇";$("soundToggle").onclick=function(){localStorage.setItem(SOUND_KEY,soundOn()?"0":"1");this.textContent=soundOn()?"🔊":"🔇";if(!soundOn()&&global.speechSynthesis)speechSynthesis.cancel()};$("talkForm").onsubmit=function(e){e.preventDefault();send($("userMessage").value)};$("userMessage").oninput=autoSize;$("userMessage").onkeydown=function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send(this.value)}};$("hintButton").onclick=function(){var h=$("helpBox");h.textContent=scene.hint;h.hidden=!h.hidden};$("repeatButton").onclick=function(){speak(lastReply)};$("finishButton").onclick=finish;$("leaveScene").onclick=function(){if(global.speechSynthesis)speechSynthesis.cancel();stopSceneVideo();setView("picker")};$("chooseAnother").onclick=function(){stopSceneVideo();state.completed=false;save();setView("picker")};$("continueStory").onclick=function(){state.completed=false;state.progress=70;save();startScene(state.sceneId,true)};$("micButton").onclick=function(){if(!recognition)return;try{recognition.start()}catch(e){}};global.addEventListener("dh-ai-source",function(e){source(e.detail)});setupRecognition();if(state.sceneId&&!state.completed&&state.messages&&state.messages.length)startScene(state.sceneId,true);else setView("picker")}
global.DHImmersive={parseReply:parseReply};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})(window);
