(function(global){"use strict";
var $=function(id){return document.getElementById(id)},api=null,records=[],record=null,study=null,segments=[],queue=[],position=0,mode="production",player=null,playerReady=false,loopOn=false,loopTimer=null,muted=false,mediaStream=null,mediaRecorder=null,chunks=[],ownAudioUrl="",youglishWidget=null,youglishLoading=false,pendingYouglishQuery="";
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function clock(v){v=Math.max(0,Math.floor(+v||0));var m=Math.floor(v/60),s=v%60;return String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}
function keyOf(x){return String(x&&x.sentenceKey||(Math.round(+x.startSeconds||0)+"|"+String(x&&x.transcriptEN||"").toLowerCase().replace(/[^a-z0-9']+/g," ").trim()))}
function state(){study.userState=study.userState&&typeof study.userState==="object"?study.userState:{};var s=study.userState;s.learned=s.learned||{};s.hard=s.hard||{};s.favorites=s.favorites||{};s.videoPractice=s.videoPractice||{cursor:0,attempts:{}};s.videoPractice.attempts=s.videoPractice.attempts||{};return s}
function validSegment(x){return x&&String(x.transcriptEN||"").trim()&&String(x.translationTR||"").trim()&&isFinite(+x.startSeconds)&&isFinite(+x.endSeconds)&&+x.endSeconds>+x.startSeconds}
function shuffle(a){a=a.slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t}return a}
function normalizeText(v){return String(v||"").toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9' ]+/g," ").replace(/\s+/g," ").trim()}
function similarity(a,b){a=normalizeText(a);b=normalizeText(b);if(!a||!b)return 0;if(a===b)return 100;var A=a.split(" "),B=b.split(" "),counts={},hits=0;B.forEach(function(w){counts[w]=(counts[w]||0)+1});A.forEach(function(w){if(counts[w]){hits++;counts[w]--}});return Math.round(200*hits/Math.max(1,A.length+B.length))}
function youglishPhrase(v){var parts=normalizeText(v).split(" ").filter(Boolean),fillers={hello:1,hi:1,hey:1,well:1,okay:1,ok:1,yes:1,no:1,so:1,please:1},starts={can:1,could:1,would:1,will:1,should:1,may:1,might:1,do:1,does:1,did:1,is:1,are:1,am:1,was:1,were:1,have:1,has:1,had:1,how:1,what:1,where:1,when:1,why:1},be={is:1,are:1,am:1,was:1,were:1},modal={can:1,could:1,would:1,will:1,should:1,may:1,might:1},prep={for:1,to:1,with:1,about:1,at:1,in:1,on:1,from:1,by:1,of:1};while(parts.length&&fillers[parts[0]])parts.shift();var at=-1;for(var i=0;i<Math.min(parts.length,5);i++)if(starts[parts[i]]){at=i;break}if(at>0)parts=parts.slice(at);if(!parts.length)return"";if(parts.length<=3)return parts.join(" ");var first=parts[0],end=4;if(modal[first]){end=first==="would"&&parts[2]==="mind"?4:3;if(parts[2]==="be")end=4}else if(be[first]){end=3;for(i=2;i<Math.min(parts.length,6);i++){end=i+1;if(prep[parts[i]])break}}else if(first==="do"||first==="does"||first==="did"||first==="have"||first==="has"||first==="had")end=4;else end=Math.min(5,parts.length);return parts.slice(0,Math.min(end,parts.length)).join(" ")}
function youglishCandidates(v){var result=[],seen={},plain=normalizeText(v),primary=youglishPhrase(v),longStatement=plain.split(" ").length>8&&!/[?]\s*$/.test(String(v||"").trim());function add(words){var q=normalizeText(Array.isArray(words)?words.join(" "):words),n=q?q.split(" ").length:0;if(n<2||n>6||seen[q])return;seen[q]=1;result.push(q)}if(!longStatement){add(primary);var pp=primary.split(" ");if(pp.length>3&&/^(for|to|with|about|at|in|on|from|by|of)$/.test(pp[pp.length-1]))add(pp.slice(0,-1))}String(v||"").split(/[.!?;:]+/).forEach(function(raw){var w=normalizeText(raw).split(" ").filter(Boolean),i,end;if(w.length<2)return;while(w.length&&/^(hello|hi|hey|well|okay|ok|yes|no|so|please)$/.test(w[0]))w.shift();if(w.length<2)return;if(w[0]==="the"&&w.length>2&&(w[2]==="is"||w[2]==="are"))add(w.slice(0,3));for(i=1;i<w.length;i++)if(/^(is|are|was|were)$/.test(w[i])&&i<4){var after=w.slice(i+1);while(after.length&&after[0]==="not")after.shift();end=after.findIndex(function(x,j){return j>=3&&/^(even|but|because|although|while)$/.test(x)});if(end<0)end=Math.min(5,after.length);add(after.slice(0,end));break}for(i=1;i<w.length-2;i++)if(/^(that|which|who)$/.test(w[i])){var begin=i>1&&/^(a|an|the|my|your|our|their)$/.test(w[i-2])?i-2:i-1;end=i+3;while(end<w.length&&end-begin<6&&!/^(even|but|because|although|while)$/.test(w[end]))end++;add(w.slice(begin,end));break}for(i=0;i<w.length-2;i++)if((w[i]==="even"&&(w[i+1]==="when"||w[i+1]==="if"))||/^(because|although|while)$/.test(w[i])){add(w.slice(i,Math.min(w.length,i+5)));break}if(w.length<=6)add(w)});if(longStatement)add(primary);return result.slice(0,6)}
function renderYouglishSuggestions(x){var box=$("youglishSuggestions"),items=youglishCandidates(x&&x.transcriptEN||"");if(!items.length){box.innerHTML="";return}box.innerHTML='<span>ARAMA ALTERNATİFLERİ</span><div>'+items.map(function(q,i){return'<button type="button" data-youglish-query="'+esc(q)+'"'+(i===0?' class="is-selected"':'')+'>'+esc(q)+'</button>'}).join("")+'</div>';Array.prototype.forEach.call(box.querySelectorAll("[data-youglish-query]"),function(btn){btn.onclick=function(){var q=btn.getAttribute("data-youglish-query");Array.prototype.forEach.call(box.querySelectorAll("button"),function(n){n.classList.toggle("is-selected",n===btn)});$("youglishQuery").value=q;fetchYouglish(q)}})}
function youglishUrl(q){return"https://youglish.com/pronounce/"+encodeURIComponent(q||"")+"/english"}
function updateYouglishLink(q){$("openYouglish").href=youglishUrl(q)}
function loadYouglishApi(){if(global.YG){createYouglishWidget();return}if(youglishLoading)return;youglishLoading=true;$("youglishStatus").textContent="YouGlish bileşeni yükleniyor…";var tag=document.createElement("script");tag.src="https://youglish.com/public/emb/widget.js";tag.async=true;tag.charset="utf-8";tag.onerror=function(){youglishLoading=false;$("youglishStatus").innerHTML='Bileşen yüklenemedi. <a href="'+esc(youglishUrl(pendingYouglishQuery))+'" target="_blank" rel="noopener">YouGlish’te açın.</a>'};document.head.appendChild(tag)}
function createYouglishWidget(){youglishLoading=false;if(youglishWidget||!global.YG||!YG.Widget)return;try{youglishWidget=new YG.Widget("youglishWidget",{autoStart:0,components:220,restrictionMode:1,backgroundColor:"#081827",panelsBackgroundColor:"#0d2134",textColor:"#b9c9db",titleColor:"#eef5ff",captionColor:"#dce8f5",keywordColor:"#55e6d1",markerColor:"#ffca63",captionSize:30,events:{onFetchDone:function(e){var total=+e.totalResult||0;$("youglishStatus").textContent=total?total+" gerçek kullanım bulundu. Oynatıp sonraki örneklere geçebilirsin.":"Bu kalıp için sonuç bulunamadı; kalıbı kısaltıp yeniden deneyin."},onError:function(){$("youglishStatus").textContent="YouGlish örneği oynatılamadı. Dış bağlantıyı kullanabilirsiniz."}}});if(pendingYouglishQuery)fetchYouglish(pendingYouglishQuery)}catch(e){$("youglishStatus").textContent="YouGlish bileşeni başlatılamadı. Dış bağlantıyı kullanabilirsiniz."}}
global.onYouglishAPIReady=function(){createYouglishWidget()};
function fetchYouglish(q){q=String(q||"").trim();if(!q)return;pendingYouglishQuery=q;updateYouglishLink(q);$("youglishStatus").textContent="“"+q+"” gerçek konuşmalarda aranıyor…";stopLoop(true);if(youglishWidget){try{youglishWidget.fetch(q,"english")}catch(e){$("youglishStatus").textContent="Arama başlatılamadı. YouGlish bağlantısını kullanabilirsiniz."}}else loadYouglishApi()}
function setMedia(kind){var useYouglish=kind==="youglish"&&!!current();if(useYouglish){stopLoop(true);$("videoView").hidden=true;$("youglishPanel").hidden=false}else{if(youglishWidget&&typeof youglishWidget.pause==="function")try{youglishWidget.pause()}catch(e){}$("youglishPanel").hidden=true;$("videoView").hidden=false}$("showVideo").classList.toggle("is-active",!useYouglish);$("showYouglish").classList.toggle("is-active",useYouglish);$("showYouglish").setAttribute("aria-pressed",String(useYouglish));$("showVideo").setAttribute("aria-pressed",String(!useYouglish))}
function openYouglishPanel(){var x=current();if(!x)return;var choices=youglishCandidates(x.transcriptEN),q=choices[0]||youglishPhrase(x.transcriptEN);toggleTranscript(false);$("youglishQuery").value=q;updateYouglishLink(q);renderYouglishSuggestions(x);$("youglishStatus").textContent="Bir kalıba dokun veya arama alanını düzenle.";setMedia("youglish")}
function closeYouglishPanel(){setMedia("video");var x=current();if(x&&playerReady)playerCall("seekTo",+x.startSeconds||0,true)}
function renderTranscript(){var box=$("transcriptList");if(!segments.length){box.innerHTML='<div class="yp-empty">Transkript bulunamadı.</div>';return}box.innerHTML=segments.map(function(x,i){return'<button type="button" data-transcript-index="'+i+'"><time>'+clock(x.startSeconds)+'</time><span><b lang="en">'+esc(x.transcriptEN)+'</b><small lang="tr">'+esc(x.translationTR)+'</small></span></button>'}).join("");Array.prototype.forEach.call(box.querySelectorAll("[data-transcript-index]"),function(btn){btn.onclick=function(){var i=+btn.getAttribute("data-transcript-index");queue=segments.slice();position=Math.max(0,Math.min(queue.length-1,i));toggleTranscript(false);renderQuestion();playerCall("seekTo",+current().startSeconds||0,true)}})}
function toggleTranscript(show){var panel=$("transcriptPicker"),open=show==null?!panel.open:!!show;panel.open=open;$("transcriptToggle").classList.toggle("is-active",open);$("transcriptToggle").setAttribute("aria-expanded",String(open));if(open){setMedia("video");renderTranscript();setTimeout(function(){var active=panel.querySelector('[data-transcript-index="'+Math.max(0,segments.indexOf(current()))+'"]');if(active){active.classList.add("is-active");active.scrollIntoView({block:"nearest"})}},0)}}
function moveSentence(delta){if(!queue.length&&segments.length){queue=segments.slice();position=0}var target=position+delta;if(target<0||target>=queue.length)return;position=target;state().videoPractice.cursor=Math.max(0,segments.indexOf(current()));saveStudy();toggleTranscript(false);renderQuestion();playerCall("seekTo",+current().startSeconds||0,true)}
function current(){return queue[position]||null}
function isPlaying(){try{return playerReady&&global.YT&&player.getPlayerState()===YT.PlayerState.PLAYING}catch(e){return false}}
function playerCall(name){if(!playerReady||!player||typeof player[name]!=="function")return;try{return player[name].apply(player,Array.prototype.slice.call(arguments,1))}catch(e){}}
function stopLoop(pause){clearInterval(loopTimer);loopTimer=null;loopOn=false;$("loopClip").classList.remove("is-active");$("loopClip").setAttribute("aria-pressed","false");if(pause)playerCall("pauseVideo")}
function playClip(forceLoop){var x=current();if(!x||!playerReady)return;toggleTranscript(false);setMedia("video");loopOn=forceLoop==null?loopOn:!!forceLoop;playerCall("seekTo",+x.startSeconds||0,true);playerCall("playVideo");clearInterval(loopTimer);loopTimer=setInterval(function(){if(!playerReady||!current())return;var y=current(),now=+playerCall("getCurrentTime")||0;if(now>=+y.endSeconds-.06||now<+y.startSeconds-.8){if(loopOn){playerCall("seekTo",+y.startSeconds||0,true);playerCall("playVideo")}else{playerCall("pauseVideo");clearInterval(loopTimer);loopTimer=null}}},120)}
function setLoop(){loopOn=!loopOn;$("loopClip").classList.toggle("is-active",loopOn);$("loopClip").setAttribute("aria-pressed",String(loopOn));if(loopOn)playClip(true);else clearInterval(loopTimer)}
function showFallback(){var f=$("playerFallback");f.hidden=false;$("openYouTube").href=record&&record.url||("https://www.youtube.com/watch?v="+(record&&record.videoId||""))}
function createPlayer(){playerReady=false;$("playerFallback").hidden=true;var node=$("ytPracticePlayer");node.innerHTML="";if(!global.YT||!YT.Player){setTimeout(createPlayer,250);return}try{player=new YT.Player("ytPracticePlayer",{host:"https://www.youtube-nocookie.com",videoId:record.videoId,playerVars:{playsinline:1,rel:0,controls:1,cc_load_policy:0,origin:location.origin&&location.origin!=="null"?location.origin:undefined},events:{onReady:function(){playerReady=true;if(current())playerCall("seekTo",+current().startSeconds||0,true)},onError:showFallback}})}catch(e){showFallback()}}
function renderLibrary(){var box=$("videoLibrary");if(!records.length){box.innerHTML='<div class="yp-empty">Henüz kayıtlı YouTube dersi yok. Önce Eğitim Stüdyosu’nda bir video kaydedin.<br><br><a href="./youtube-egitim.html" style="color:var(--cyan)">Eğitim Stüdyosu’nu aç</a></div>';return}box.innerHTML=records.map(function(r){var data=r.study||{},count=Array.isArray(data.segments)?data.segments.filter(validSegment).length:0,thumb="https://i.ytimg.com/vi/"+encodeURIComponent(r.videoId)+"/hqdefault.jpg";return'<button class="yp-video-card" type="button" data-video="'+esc(r.videoId)+'"><span class="yp-thumb" style="background-image:url(\''+thumb+'\')"><i>▶</i></span><span><strong>'+esc(r.title||data.title||"YouTube çalışması")+'</strong><small>'+esc(data.level||r.level||"")+" · "+count+' çalışılabilir cümle</small></span></button>'}).join("");Array.prototype.forEach.call(box.querySelectorAll("[data-video]"),function(b){b.onclick=function(){openVideo(b.getAttribute("data-video"))}})}
function openVideo(id){record=records.filter(function(r){return String(r.videoId)===String(id)})[0];if(!record)return;study=api.normalize(record.study);segments=study.segments.filter(validSegment);$("libraryView").hidden=true;$("practiceView").hidden=false;$("videoTitle").textContent=study.title||record.title||"YouTube çalışması";$("videoLevel").textContent=(study.level||"—")+" · YOUTUBE";$("videoStats").textContent=segments.length+" cümle · görüntü temelli pratik";$("openYouTube").href=record.url||api.canonical(record.videoId);queue=[];position=0;renderTranscript();renderQuestion();createPlayer()}
function buildQueue(){var s=state(),filter=$("sentenceFilter").value,size=Math.max(1,+$("sessionSize").value||15),pool=segments.slice();if(filter==="unlearned")pool=pool.filter(function(x){return!s.learned[keyOf(x)]});else if(filter==="hard")pool=pool.filter(function(x){return!!s.hard[keyOf(x)]});else if(filter==="favorites")pool=pool.filter(function(x){return!!s.favorites[keyOf(x)]});if(filter==="continue"&&pool.length){var start=Math.max(0,Math.min(pool.length-1,+s.videoPractice.cursor||0));pool=pool.slice(start).concat(pool.slice(0,start))}else if(filter!=="all")pool=shuffle(pool);queue=pool.slice(0,size);position=0;if(!queue.length){$("questionArea").innerHTML='<div class="yp-empty">Bu filtreye uygun cümle bulunamadı.</div>';return}renderQuestion();playerCall("seekTo",+current().startSeconds||0,true)}
function modeName(){return{production:"TR → EN",dictation:"DİKTE",context:"BAĞLAM",shadow:"SHADOWING"}[mode]||"YOUTUBE"}
function answerForm(placeholder){return'<form class="yp-answer" id="answerForm"><textarea id="answerInput" autocomplete="off" placeholder="'+esc(placeholder)+'"></textarea><button type="submit">Kontrol et</button></form>'}
function renderProduction(x){$("questionArea").innerHTML='<p class="yp-prompt" lang="tr">'+esc(x.translationTR)+'</p><p class="yp-hint">Video görüntüsünü bağlam olarak kullan; İngilizce cümleyi yaz.</p>'+answerForm("İngilizcesini yaz…");$("answerForm").onsubmit=function(e){e.preventDefault();checkWritten($("answerInput").value)}}
function renderDictation(x){$("questionArea").innerHTML='<p class="yp-prompt">Videoyu dinle ve duyduğunu yaz</p><p class="yp-hint">Altyazı gösterilmez. Kesiti istediğin kadar yeniden oynatabilirsin.</p>'+answerForm("Duyduğun İngilizceyi yaz…");$("answerForm").onsubmit=function(e){e.preventDefault();checkWritten($("answerInput").value)};setTimeout(function(){playClip(false)},120)}
function renderContext(x){var others=shuffle(segments.filter(function(y){return y!==x&&y.translationTR!==x.translationTR})).slice(0,3),options=shuffle([x].concat(others));$("questionArea").innerHTML='<p class="yp-prompt">Video kesitinin anlamı hangisi?</p><p class="yp-hint">Görüntü ve ses bağlamını kullan.</p><div class="yp-context-options">'+options.map(function(o){return'<button type="button" data-context="'+esc(keyOf(o))+'">'+esc(o.translationTR)+'</button>'}).join("")+'</div>';Array.prototype.forEach.call(document.querySelectorAll("[data-context]"),function(b){b.onclick=function(){var ok=b.getAttribute("data-context")===keyOf(x);Array.prototype.forEach.call(document.querySelectorAll("[data-context]"),function(n){n.disabled=true;if(n.getAttribute("data-context")===keyOf(x))n.classList.add("correct")});if(!ok)b.classList.add("wrong");finishAttempt(ok?100:0,ok?"Doğru anlamı yakaladın.":"Doğru cevap: "+x.translationTR)}});setTimeout(function(){playClip(false)},120)}
function renderShadow(x){$("questionArea").innerHTML='<p class="yp-prompt" lang="en">'+esc(x.transcriptEN)+'</p><p class="yp-hint" lang="tr">'+esc(x.translationTR)+'</p><div class="yp-shadow-actions"><button id="shadowOriginal" type="button">▶ Özgün kesiti dinle</button><button id="shadowRecord" type="button">🎙 Kaydı başlat</button><button id="shadowOwn" type="button" disabled>▶ Kendi sesim</button><button id="shadowStudio" type="button">Stüdyoda ayrıntılı çalış</button></div><p class="yp-record-status" id="recordStatus">Önce özgün kesiti dinle, sonra görüntüyle birlikte kaydet.</p>';$("shadowOriginal").onclick=function(){muted=false;playerCall("unMute");playClip(false)};$("shadowRecord").onclick=toggleRecording;$("shadowOwn").onclick=playOwnRecording;$("shadowStudio").onclick=function(){location.href="./youtube-egitim.html?video="+encodeURIComponent(record.videoId)} }
function renderQuestion(){stopLoop(false);stopRecording(true);closeYouglishPanel();toggleTranscript(false);$("feedback").hidden=true;$("gradeActions").hidden=true;var x=current();$("modeLabel").textContent=modeName();$("questionNumber").textContent="CÜMLE "+(x?position+1:0)+" / "+queue.length;$("previousSentence").disabled=!x||position<=0;$("nextSentenceSkip").disabled=!x||position>=queue.length-1;$("showYouglish").disabled=!x;$("transcriptToggle").disabled=!segments.length;if(!x){$("questionArea").innerHTML='<div class="yp-empty">Soldan filtreleri seçip “Oturumu hazırla” düğmesine bas.</div>';$("clipTime").textContent="00:00–00:00";$("youglishScenes").disabled=true;return}$("youglishScenes").disabled=false;$("clipTime").textContent=clock(x.startSeconds)+"–"+clock(x.endSeconds);if(mode==="production")renderProduction(x);else if(mode==="dictation")renderDictation(x);else if(mode==="context")renderContext(x);else renderShadow(x)}
function checkWritten(value){var x=current(),score=similarity(value,x.transcriptEN),ok=score>=85;finishAttempt(score,(ok?"Anlam ve cümle yapısı doğru.":"Doğru cevap: ")+x.transcriptEN);if(!ok&&global.LearningErrorDB&&LearningErrorDB.logFromVideo)LearningErrorDB.logFromVideo({sentence:{id:"yt:"+record.videoId+":"+keyOf(x),en:x.transcriptEN,tr:x.translationTR,level:study.level,module:study.title},heard:value,grade:"hard",score:score,mode:mode}).catch(function(){})}
function finishAttempt(score,message){var box=$("feedback");box.hidden=false;box.className="yp-feedback "+(score>=85?"good":"bad");box.innerHTML='<b>%'+Math.max(0,Math.min(100,Math.round(score)))+'</b> · '+esc(message);$("gradeActions").hidden=false;var s=state(),x=current();s.videoPractice.attempts[keyOf(x)]={score:score,mode:mode,at:Date.now()};saveStudy()}
function grade(type){var x=current();if(!x)return;var s=state(),k=keyOf(x);if(type==="learned"){s.learned[k]=true;delete s.hard[k]}else{s.hard[k]=true;delete s.learned[k]}saveStudy();next()}
function next(){if(position<queue.length-1){position++;state().videoPractice.cursor=Math.max(0,segments.indexOf(current()));saveStudy();renderQuestion();playerCall("seekTo",+current().startSeconds||0,true)}else{$("questionArea").innerHTML='<div class="yp-empty"><b>Oturum tamamlandı.</b><br>'+queue.length+' cümleyi video bağlamıyla çalıştın.</div>';$("feedback").hidden=true;$("gradeActions").hidden=true;$("questionNumber").textContent="TAMAMLANDI";stopLoop(true)}}
function saveStudy(){if(!api||!record||!study)return;clearTimeout(saveStudy.timer);saveStudy.timer=setTimeout(function(){api.save(record.videoId,record.url||api.canonical(record.videoId),study).catch(function(){})},350)}
async function toggleRecording(){if(mediaRecorder&&mediaRecorder.state==="recording"){stopRecording(false);return}if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){$("recordStatus").textContent="Bu tarayıcı mikrofon kaydını desteklemiyor.";return}try{mediaStream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];mediaRecorder=new MediaRecorder(mediaStream);mediaRecorder.ondataavailable=function(e){if(e.data&&e.data.size)chunks.push(e.data)};mediaRecorder.onstop=saveRecording;mediaRecorder.start();muted=true;playerCall("mute");loopOn=true;playClip(true);$("shadowRecord").textContent="■ Kaydı bitir";$("shadowRecord").classList.add("recording");$("recordStatus").textContent="Kayıt yapılıyor · görüntü cümle aralığında sessiz dönüyor."}catch(e){$("recordStatus").textContent="Mikrofon açılamadı. Tarayıcı iznini kontrol edin."}}
function stopRecording(silent){if(mediaRecorder&&mediaRecorder.state==="recording")try{mediaRecorder.stop()}catch(e){}if(mediaStream){mediaStream.getTracks().forEach(function(t){t.stop()});mediaStream=null}if($("shadowRecord")){$("shadowRecord").textContent="🎙 Kaydı başlat";$("shadowRecord").classList.remove("recording")}if(silent){chunks=[];mediaRecorder=null}}
function saveRecording(){var x=current();if(!x||!chunks.length)return;var blob=new Blob(chunks,{type:mediaRecorder&&mediaRecorder.mimeType||"audio/webm"});chunks=[];if(ownAudioUrl)URL.revokeObjectURL(ownAudioUrl);ownAudioUrl=URL.createObjectURL(blob);$("shadowOwn").disabled=false;$("recordStatus").textContent="✓ Kayıt bu cümleye kaydedildi.";var box=$("feedback");box.hidden=false;box.className="yp-feedback good";box.textContent="Shadowing kaydı tamamlandı. Kendi sesini dinleyebilir veya cümleyi işaretleyip devam edebilirsin.";$("gradeActions").hidden=false;state().videoPractice.attempts[keyOf(x)]={mode:"shadow",recorded:true,at:Date.now()};saveStudy();api.saveShadowAudio(record.videoId,keyOf(x),blob,{startSeconds:x.startSeconds,endSeconds:x.endSeconds,transcriptEN:x.transcriptEN}).catch(function(){$("recordStatus").textContent="Kayıt dinlenebilir ancak kalıcı saklanamadı."})}
function playOwnRecording(){if(!ownAudioUrl)return;stopLoop(false);playerCall("seekTo",+current().startSeconds||0,true);playerCall("playVideo");playerCall("mute");var a=new Audio(ownAudioUrl);a.play().catch(function(){});a.onended=function(){playerCall("pauseVideo")}}
global.DHVideoPracticeUI={toggleTranscript:toggleTranscript};
function bind(){$("changeVideo").onclick=function(){stopLoop(true);closeYouglishPanel();toggleTranscript(false);$("practiceView").hidden=true;$("libraryView").hidden=false};$("startSession").onclick=buildQueue;$("replayClip").onclick=function(){playClip(false)};$("loopClip").onclick=setLoop;$("muteClip").onclick=function(){muted=!muted;playerCall(muted?"mute":"unMute");this.textContent=muted?"🔇 Sessiz":"🔊 Ses";this.setAttribute("aria-pressed",String(muted))};$("showVideo").onclick=closeYouglishPanel;$("showYouglish").onclick=openYouglishPanel;$("youglishScenes").onclick=openYouglishPanel;$("closeYouglish").onclick=closeYouglishPanel;$("backToPractice").onclick=closeYouglishPanel;$("previousSentence").onclick=function(){moveSentence(-1)};$("nextSentenceSkip").onclick=function(){moveSentence(1)};$("youglishSearch").onsubmit=function(e){e.preventDefault();fetchYouglish($("youglishQuery").value)};$("nextQuestion").onclick=next;Array.prototype.forEach.call(document.querySelectorAll("[data-grade]"),function(b){b.onclick=function(){grade(b.getAttribute("data-grade"))}});Array.prototype.forEach.call(document.querySelectorAll("[data-mode]"),function(b){b.onclick=function(){mode=b.getAttribute("data-mode");Array.prototype.forEach.call(document.querySelectorAll("[data-mode]"),function(n){n.classList.toggle("is-active",n===b)});renderQuestion()}})}
async function boot(){bind();api=global.DHYouTubeStudy;if(!api){$("videoLibrary").innerHTML='<div class="yp-empty">YouTube ders veri katmanı yüklenemedi.</div>';return}try{await api.applyMirror().catch(function(){});records=(await api.all()).filter(function(r){return r&&r.study&&Array.isArray(r.study.segments)&&r.study.segments.some(validSegment)});renderLibrary()}catch(e){$("videoLibrary").innerHTML='<div class="yp-empty">Kayıtlı videolar okunamadı.</div>'}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})(window);
